image: gitpod/workspace-full

tasks:
    - name: run
      command: |
          apt-get update && apt-get install -yq \
          git \
          git-lfs \
          sudo \
          sra-toolkit \
          parallel \
          fastqc \
          cutadapt \
          curl \
          ncbi-blast+ \
          && rm -rf /var/lib/apt/lists/* /tmp/*
    - name: Trim_Galore
      command: |
         curl -fsSL https://github.com/FelixKrueger/TrimGalore/archive/0.6.10.tar.gz -o trim_galore.tar.gz
         tar xvzf trim_galore.tar.gz
    - name: usearch
      command: |
        chmod a+x usearch
