image:
    file: .gitpod.Dockerfile
tasks:
- name: Trim_Galore
  command: |
    curl -fsSL https://github.com/FelixKrueger/TrimGalore/archive/0.6.10.tar.gz -o trim_galore.tar.gz
    tar xvzf trim_galore.tar.gz

- name: USEARCH
  command: |
    curl -fsSL https://github.com/ezzbioinf/Marine-environmental-DNA-metabarcoding-data-analyses-practical-11-13-October-2023/blob/master/usearch -o usearch
    chmod a+x usearch
    sudo mv usearch /usr/local/bin/
